---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-customer
  namespace: nautible-app
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nautible-app-customer
        image: nautibledevacr.azurecr.io/nautible-app-customer:latest
        env:
        - name: QUARKUS_PROFILE
          value: azure-local-dev
#        - name: JAVA_VERSION
#          value: "11"
