---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-ms-customer
  namespace: nautible-app-ms
spec:
  template:
    spec:
      containers:
      - name: nautible-app-ms-customer
        image: public.ecr.aws/nautible/nautible-app-ms-customer:f2e729f7be1732d6b48c04619c0b8d4e4b36d691
        env:
        - name: QUARKUS_PROFILE
          value: aws-dev
        - name: QUARKUS_DYNAMODB_AWS_REGION
          value: ap-northeast-1
