---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-ms-customer
  namespace: nautible-app-ms
spec:
  template:
    spec:
      containers:
      - name: nautible-app-ms-customer
        image: public.ecr.aws/nautible/nautible-app-ms-customer:3c9ed9c0e11d1f1e0d947371c2f59e87c9855f10
        env:
        - name: QUARKUS_PROFILE
          value: aws-dev
        - name: QUARKUS_DYNAMODB_AWS_REGION
          value: ap-northeast-1
