---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-customer
  namespace: nautible-app
spec:
  template:
    spec:
      containers:
      - name: nautible-app-customer
        image: nautibledevacr.azurecr.io/nautible-app-customer:6033f55fd7b5403b7a439acae3ba1599eddef2d8
        env:
        - name: QUARKUS_PROFILE
          value: azure-dev
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: secret-nautible-app-cosmosdb
              key: DATABASE_USER
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: secret-nautible-app-cosmosdb
              key: DATABASE_PW
