---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-customer
  namespace: nautible-app
spec:
  template:
    spec:
      containers:
      - name: nautible-app-customer
        image: nautibledevacr.azurecr.io/nautible-app-customer:311645b3857f379ec6d9e8e18ea439b2a9298697
        env:
        - name: QUARKUS_PROFILE
          value: azure-dev
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: secret-nautible-app-cosmosdb
              key: DATABASE_USER
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: secret-nautible-app-cosmosdb
              key: DATABASE_PW
