---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-ms-customer
  namespace: nautible-app-ms
spec:
  template:
    spec:
      containers:
      - name: nautible-app-ms-customer
        image: nautibledevacr.azurecr.io/nautible-app-ms-customer:a19720b65421b4b9306f4fd7371345c635e8b2a2
        env:
        - name: QUARKUS_PROFILE
          value: azure-dev
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: secret-nautible-app-ms-cosmosdb
              key: DATABASE_USER
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: secret-nautible-app-ms-cosmosdb
              key: DATABASE_PW
